import * as MoleculerTs from 'moleculer-ts';
import * as Broker from './moleculer';
import * as Services from './services.types';

export interface ServiceBroker {
  call<T extends ServiceActionNames>(
    actionName: T,
    params: GetCallParams[T],
    opts?: Broker.CallingOptions,
  ): PromiseLike<GetCallReturn[T]>;

  emit<T extends ServiceEventNames>(
    eventName: T,
    payload: GetEmitParams[T],
    groups?: ServiceNamesEmitGroup,
  ): void;

  broadcast: ServiceBroker['emit'];
  broadcastLocal: ServiceBroker['emit'];
}

type GetCallParams = {
  'db.accounts': Services.DbServiceTypes.Actions[0]['in'];
  'db.countAccounts': Services.DbServiceTypes.Actions[1]['in'];
  'db.firstAccounts': Services.DbServiceTypes.Actions[2]['in'];
  'db.firstAccounts.user': Services.DbServiceTypes.Actions[3]['in'];
  'db.findAccounts': Services.DbServiceTypes.Actions[4]['in'];
  'db.migrations': Services.DbServiceTypes.Actions[5]['in'];
  'db.countMigrations': Services.DbServiceTypes.Actions[6]['in'];
  'db.firstMigrations': Services.DbServiceTypes.Actions[7]['in'];
  'db.findMigrations': Services.DbServiceTypes.Actions[8]['in'];
  'db.testMultiplePrimaries': Services.DbServiceTypes.Actions[9]['in'];
  'db.countTestMultiplePrimaries': Services.DbServiceTypes.Actions[10]['in'];
  'db.firstTestMultiplePrimaries': Services.DbServiceTypes.Actions[11]['in'];
  'db.findTestMultiplePrimaries': Services.DbServiceTypes.Actions[12]['in'];
  'db.testPrimaries': Services.DbServiceTypes.Actions[13]['in'];
  'db.countTestPrimaries': Services.DbServiceTypes.Actions[14]['in'];
  'db.firstTestPrimaries': Services.DbServiceTypes.Actions[15]['in'];
  'db.findTestPrimaries': Services.DbServiceTypes.Actions[16]['in'];
  'db.users': Services.DbServiceTypes.Actions[17]['in'];
  'db.countUsers': Services.DbServiceTypes.Actions[18]['in'];
  'db.firstUsers': Services.DbServiceTypes.Actions[19]['in'];
  'db.firstUsers.profile': Services.DbServiceTypes.Actions[20]['in'];
  'db.findUsers': Services.DbServiceTypes.Actions[21]['in'];
  'db.userProfiles': Services.DbServiceTypes.Actions[22]['in'];
  'db.countUserProfiles': Services.DbServiceTypes.Actions[23]['in'];
  'db.firstUserProfiles': Services.DbServiceTypes.Actions[24]['in'];
  'db.firstUserProfiles.user': Services.DbServiceTypes.Actions[25]['in'];
  'db.findUserProfiles': Services.DbServiceTypes.Actions[26]['in'];
  'db.account': Services.DbServiceTypes.Actions[27]['in'];
  'db.account.user': Services.DbServiceTypes.Actions[28]['in'];
  'db.migration': Services.DbServiceTypes.Actions[29]['in'];
  'db.testMultiplePrimary': Services.DbServiceTypes.Actions[30]['in'];
  'db.testPrimary': Services.DbServiceTypes.Actions[31]['in'];
  'db.user': Services.DbServiceTypes.Actions[32]['in'];
  'db.user.profile': Services.DbServiceTypes.Actions[33]['in'];
  'db.userByEmail': Services.DbServiceTypes.Actions[34]['in'];
  'db.userByEmail.profile': Services.DbServiceTypes.Actions[35]['in'];
  'db.userByFirstNameAndLastName': Services.DbServiceTypes.Actions[36]['in'];
  'db.userByFirstNameAndLastName.profile': Services.DbServiceTypes.Actions[37]['in'];
  'db.userByUserProfileId': Services.DbServiceTypes.Actions[38]['in'];
  'db.userByUserProfileId.profile': Services.DbServiceTypes.Actions[39]['in'];
  'db.userProfile': Services.DbServiceTypes.Actions[40]['in'];
  'db.userProfile.user': Services.DbServiceTypes.Actions[41]['in'];
  'db.userSearch': Services.DbServiceTypes.Actions[42]['in'];
  'db.countUserSearch': Services.DbServiceTypes.Actions[43]['in'];
  'db.firstUserSearch': Services.DbServiceTypes.Actions[44]['in'];
  'db.firstUserSearch.profile': Services.DbServiceTypes.Actions[45]['in'];
  'db.findUserSearch': Services.DbServiceTypes.Actions[46]['in'];
  'db.createAccount': Services.DbServiceTypes.Actions[47]['in'];
  'db.createMigration': Services.DbServiceTypes.Actions[48]['in'];
  'db.createTestMultiplePrimary': Services.DbServiceTypes.Actions[49]['in'];
  'db.createTestPrimary': Services.DbServiceTypes.Actions[50]['in'];
  'db.createUser': Services.DbServiceTypes.Actions[51]['in'];
  'db.createUserProfile': Services.DbServiceTypes.Actions[52]['in'];
  'db.updateAccount': Services.DbServiceTypes.Actions[53]['in'];
  'db.upsertAccount': Services.DbServiceTypes.Actions[54]['in'];
  'db.updateMigration': Services.DbServiceTypes.Actions[55]['in'];
  'db.upsertMigration': Services.DbServiceTypes.Actions[56]['in'];
  'db.updateTestMultiplePrimary': Services.DbServiceTypes.Actions[57]['in'];
  'db.upsertTestMultiplePrimary': Services.DbServiceTypes.Actions[58]['in'];
  'db.updateTestPrimary': Services.DbServiceTypes.Actions[59]['in'];
  'db.upsertTestPrimary': Services.DbServiceTypes.Actions[60]['in'];
  'db.updateUser': Services.DbServiceTypes.Actions[61]['in'];
  'db.upsertUser': Services.DbServiceTypes.Actions[62]['in'];
  'db.updateUserByEmail': Services.DbServiceTypes.Actions[63]['in'];
  'db.updateUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[64]['in'];
  'db.updateUserByUserProfileId': Services.DbServiceTypes.Actions[65]['in'];
  'db.updateUserProfile': Services.DbServiceTypes.Actions[66]['in'];
  'db.upsertUserProfile': Services.DbServiceTypes.Actions[67]['in'];
  'db.deleteAccount': Services.DbServiceTypes.Actions[68]['in'];
  'db.deleteMigration': Services.DbServiceTypes.Actions[69]['in'];
  'db.deleteTestMultiplePrimary': Services.DbServiceTypes.Actions[70]['in'];
  'db.deleteTestPrimary': Services.DbServiceTypes.Actions[71]['in'];
  'db.deleteUser': Services.DbServiceTypes.Actions[72]['in'];
  'db.deleteUserByEmail': Services.DbServiceTypes.Actions[73]['in'];
  'db.deleteUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[74]['in'];
  'db.deleteUserByUserProfileId': Services.DbServiceTypes.Actions[75]['in'];
  'db.deleteUserProfile': Services.DbServiceTypes.Actions[76]['in'];
};
type GetCallReturn = {
  'db.accounts': Services.DbServiceTypes.Actions[0]['out'];
  'db.countAccounts': Services.DbServiceTypes.Actions[1]['out'];
  'db.firstAccounts': Services.DbServiceTypes.Actions[2]['out'];
  'db.firstAccounts.user': Services.DbServiceTypes.Actions[3]['out'];
  'db.findAccounts': Services.DbServiceTypes.Actions[4]['out'];
  'db.migrations': Services.DbServiceTypes.Actions[5]['out'];
  'db.countMigrations': Services.DbServiceTypes.Actions[6]['out'];
  'db.firstMigrations': Services.DbServiceTypes.Actions[7]['out'];
  'db.findMigrations': Services.DbServiceTypes.Actions[8]['out'];
  'db.testMultiplePrimaries': Services.DbServiceTypes.Actions[9]['out'];
  'db.countTestMultiplePrimaries': Services.DbServiceTypes.Actions[10]['out'];
  'db.firstTestMultiplePrimaries': Services.DbServiceTypes.Actions[11]['out'];
  'db.findTestMultiplePrimaries': Services.DbServiceTypes.Actions[12]['out'];
  'db.testPrimaries': Services.DbServiceTypes.Actions[13]['out'];
  'db.countTestPrimaries': Services.DbServiceTypes.Actions[14]['out'];
  'db.firstTestPrimaries': Services.DbServiceTypes.Actions[15]['out'];
  'db.findTestPrimaries': Services.DbServiceTypes.Actions[16]['out'];
  'db.users': Services.DbServiceTypes.Actions[17]['out'];
  'db.countUsers': Services.DbServiceTypes.Actions[18]['out'];
  'db.firstUsers': Services.DbServiceTypes.Actions[19]['out'];
  'db.firstUsers.profile': Services.DbServiceTypes.Actions[20]['out'];
  'db.findUsers': Services.DbServiceTypes.Actions[21]['out'];
  'db.userProfiles': Services.DbServiceTypes.Actions[22]['out'];
  'db.countUserProfiles': Services.DbServiceTypes.Actions[23]['out'];
  'db.firstUserProfiles': Services.DbServiceTypes.Actions[24]['out'];
  'db.firstUserProfiles.user': Services.DbServiceTypes.Actions[25]['out'];
  'db.findUserProfiles': Services.DbServiceTypes.Actions[26]['out'];
  'db.account': Services.DbServiceTypes.Actions[27]['out'];
  'db.account.user': Services.DbServiceTypes.Actions[28]['out'];
  'db.migration': Services.DbServiceTypes.Actions[29]['out'];
  'db.testMultiplePrimary': Services.DbServiceTypes.Actions[30]['out'];
  'db.testPrimary': Services.DbServiceTypes.Actions[31]['out'];
  'db.user': Services.DbServiceTypes.Actions[32]['out'];
  'db.user.profile': Services.DbServiceTypes.Actions[33]['out'];
  'db.userByEmail': Services.DbServiceTypes.Actions[34]['out'];
  'db.userByEmail.profile': Services.DbServiceTypes.Actions[35]['out'];
  'db.userByFirstNameAndLastName': Services.DbServiceTypes.Actions[36]['out'];
  'db.userByFirstNameAndLastName.profile': Services.DbServiceTypes.Actions[37]['out'];
  'db.userByUserProfileId': Services.DbServiceTypes.Actions[38]['out'];
  'db.userByUserProfileId.profile': Services.DbServiceTypes.Actions[39]['out'];
  'db.userProfile': Services.DbServiceTypes.Actions[40]['out'];
  'db.userProfile.user': Services.DbServiceTypes.Actions[41]['out'];
  'db.userSearch': Services.DbServiceTypes.Actions[42]['out'];
  'db.countUserSearch': Services.DbServiceTypes.Actions[43]['out'];
  'db.firstUserSearch': Services.DbServiceTypes.Actions[44]['out'];
  'db.firstUserSearch.profile': Services.DbServiceTypes.Actions[45]['out'];
  'db.findUserSearch': Services.DbServiceTypes.Actions[46]['out'];
  'db.createAccount': Services.DbServiceTypes.Actions[47]['out'];
  'db.createMigration': Services.DbServiceTypes.Actions[48]['out'];
  'db.createTestMultiplePrimary': Services.DbServiceTypes.Actions[49]['out'];
  'db.createTestPrimary': Services.DbServiceTypes.Actions[50]['out'];
  'db.createUser': Services.DbServiceTypes.Actions[51]['out'];
  'db.createUserProfile': Services.DbServiceTypes.Actions[52]['out'];
  'db.updateAccount': Services.DbServiceTypes.Actions[53]['out'];
  'db.upsertAccount': Services.DbServiceTypes.Actions[54]['out'];
  'db.updateMigration': Services.DbServiceTypes.Actions[55]['out'];
  'db.upsertMigration': Services.DbServiceTypes.Actions[56]['out'];
  'db.updateTestMultiplePrimary': Services.DbServiceTypes.Actions[57]['out'];
  'db.upsertTestMultiplePrimary': Services.DbServiceTypes.Actions[58]['out'];
  'db.updateTestPrimary': Services.DbServiceTypes.Actions[59]['out'];
  'db.upsertTestPrimary': Services.DbServiceTypes.Actions[60]['out'];
  'db.updateUser': Services.DbServiceTypes.Actions[61]['out'];
  'db.upsertUser': Services.DbServiceTypes.Actions[62]['out'];
  'db.updateUserByEmail': Services.DbServiceTypes.Actions[63]['out'];
  'db.updateUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[64]['out'];
  'db.updateUserByUserProfileId': Services.DbServiceTypes.Actions[65]['out'];
  'db.updateUserProfile': Services.DbServiceTypes.Actions[66]['out'];
  'db.upsertUserProfile': Services.DbServiceTypes.Actions[67]['out'];
  'db.deleteAccount': Services.DbServiceTypes.Actions[68]['out'];
  'db.deleteMigration': Services.DbServiceTypes.Actions[69]['out'];
  'db.deleteTestMultiplePrimary': Services.DbServiceTypes.Actions[70]['out'];
  'db.deleteTestPrimary': Services.DbServiceTypes.Actions[71]['out'];
  'db.deleteUser': Services.DbServiceTypes.Actions[72]['out'];
  'db.deleteUserByEmail': Services.DbServiceTypes.Actions[73]['out'];
  'db.deleteUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[74]['out'];
  'db.deleteUserByUserProfileId': Services.DbServiceTypes.Actions[75]['out'];
  'db.deleteUserProfile': Services.DbServiceTypes.Actions[76]['out'];
};
type GetEmitParams = {
  'db.emit': MoleculerTs.Union.Strict<Services.DbServiceTypes.Events[0]['in']>;
};
export type ServiceNames = Exclude<never | 'db', never>;
export type ServiceNamesEmitGroup = ServiceNames | ServiceNames[];
export type ServiceEventNames = Exclude<never | 'db.emit', never>;
export type ServiceActionNames = Exclude<
  | never
  | 'db.accounts'
  | 'db.countAccounts'
  | 'db.firstAccounts'
  | 'db.firstAccounts.user'
  | 'db.findAccounts'
  | 'db.migrations'
  | 'db.countMigrations'
  | 'db.firstMigrations'
  | 'db.findMigrations'
  | 'db.testMultiplePrimaries'
  | 'db.countTestMultiplePrimaries'
  | 'db.firstTestMultiplePrimaries'
  | 'db.findTestMultiplePrimaries'
  | 'db.testPrimaries'
  | 'db.countTestPrimaries'
  | 'db.firstTestPrimaries'
  | 'db.findTestPrimaries'
  | 'db.users'
  | 'db.countUsers'
  | 'db.firstUsers'
  | 'db.firstUsers.profile'
  | 'db.findUsers'
  | 'db.userProfiles'
  | 'db.countUserProfiles'
  | 'db.firstUserProfiles'
  | 'db.firstUserProfiles.user'
  | 'db.findUserProfiles'
  | 'db.account'
  | 'db.account.user'
  | 'db.migration'
  | 'db.testMultiplePrimary'
  | 'db.testPrimary'
  | 'db.user'
  | 'db.user.profile'
  | 'db.userByEmail'
  | 'db.userByEmail.profile'
  | 'db.userByFirstNameAndLastName'
  | 'db.userByFirstNameAndLastName.profile'
  | 'db.userByUserProfileId'
  | 'db.userByUserProfileId.profile'
  | 'db.userProfile'
  | 'db.userProfile.user'
  | 'db.userSearch'
  | 'db.countUserSearch'
  | 'db.firstUserSearch'
  | 'db.firstUserSearch.profile'
  | 'db.findUserSearch'
  | 'db.createAccount'
  | 'db.createMigration'
  | 'db.createTestMultiplePrimary'
  | 'db.createTestPrimary'
  | 'db.createUser'
  | 'db.createUserProfile'
  | 'db.updateAccount'
  | 'db.upsertAccount'
  | 'db.updateMigration'
  | 'db.upsertMigration'
  | 'db.updateTestMultiplePrimary'
  | 'db.upsertTestMultiplePrimary'
  | 'db.updateTestPrimary'
  | 'db.upsertTestPrimary'
  | 'db.updateUser'
  | 'db.upsertUser'
  | 'db.updateUserByEmail'
  | 'db.updateUserByFirstNameAndLastName'
  | 'db.updateUserByUserProfileId'
  | 'db.updateUserProfile'
  | 'db.upsertUserProfile'
  | 'db.deleteAccount'
  | 'db.deleteMigration'
  | 'db.deleteTestMultiplePrimary'
  | 'db.deleteTestPrimary'
  | 'db.deleteUser'
  | 'db.deleteUserByEmail'
  | 'db.deleteUserByFirstNameAndLastName'
  | 'db.deleteUserByUserProfileId'
  | 'db.deleteUserProfile',
  never
>;
