import * as MoleculerTs from 'moleculer-ts';
import * as Broker from './moleculer';
import * as Services from './services.types';

export interface ServiceBroker {
  call<T extends ServiceActionNames>(
    actionName: T,
    params: GetCallParams[T],
    opts?: Broker.CallingOptions,
  ): PromiseLike<GetCallReturn[T]>;

  emit<T extends ServiceEventNames>(
    eventName: T,
    payload: GetEmitParams[T],
    groups?: ServiceNamesEmitGroup,
  ): void;

  broadcast: ServiceBroker['emit'];
  broadcastLocal: ServiceBroker['emit'];
}

type GetCallParams = {
  'db.accounts': Services.DbServiceTypes.Actions[0]['in'];
  'db.countAccounts': Services.DbServiceTypes.Actions[1]['in'];
  'db.firstAccounts': Services.DbServiceTypes.Actions[2]['in'];
  'db.firstAccounts.user': Services.DbServiceTypes.Actions[3]['in'];
  'db.findAccounts': Services.DbServiceTypes.Actions[4]['in'];
  'db.migrationGenerateds': Services.DbServiceTypes.Actions[5]['in'];
  'db.countMigrationGenerateds': Services.DbServiceTypes.Actions[6]['in'];
  'db.firstMigrationGenerateds': Services.DbServiceTypes.Actions[7]['in'];
  'db.findMigrationGenerateds': Services.DbServiceTypes.Actions[8]['in'];
  'db.migrationManuals': Services.DbServiceTypes.Actions[9]['in'];
  'db.countMigrationManuals': Services.DbServiceTypes.Actions[10]['in'];
  'db.firstMigrationManuals': Services.DbServiceTypes.Actions[11]['in'];
  'db.findMigrationManuals': Services.DbServiceTypes.Actions[12]['in'];
  'db.migrationSeeds': Services.DbServiceTypes.Actions[13]['in'];
  'db.countMigrationSeeds': Services.DbServiceTypes.Actions[14]['in'];
  'db.firstMigrationSeeds': Services.DbServiceTypes.Actions[15]['in'];
  'db.findMigrationSeeds': Services.DbServiceTypes.Actions[16]['in'];
  'db.testMultiplePrimaries': Services.DbServiceTypes.Actions[17]['in'];
  'db.countTestMultiplePrimaries': Services.DbServiceTypes.Actions[18]['in'];
  'db.firstTestMultiplePrimaries': Services.DbServiceTypes.Actions[19]['in'];
  'db.findTestMultiplePrimaries': Services.DbServiceTypes.Actions[20]['in'];
  'db.testPrimaries': Services.DbServiceTypes.Actions[21]['in'];
  'db.countTestPrimaries': Services.DbServiceTypes.Actions[22]['in'];
  'db.firstTestPrimaries': Services.DbServiceTypes.Actions[23]['in'];
  'db.findTestPrimaries': Services.DbServiceTypes.Actions[24]['in'];
  'db.users': Services.DbServiceTypes.Actions[25]['in'];
  'db.countUsers': Services.DbServiceTypes.Actions[26]['in'];
  'db.firstUsers': Services.DbServiceTypes.Actions[27]['in'];
  'db.firstUsers.profile': Services.DbServiceTypes.Actions[28]['in'];
  'db.findUsers': Services.DbServiceTypes.Actions[29]['in'];
  'db.userProfiles': Services.DbServiceTypes.Actions[30]['in'];
  'db.countUserProfiles': Services.DbServiceTypes.Actions[31]['in'];
  'db.firstUserProfiles': Services.DbServiceTypes.Actions[32]['in'];
  'db.firstUserProfiles.user': Services.DbServiceTypes.Actions[33]['in'];
  'db.findUserProfiles': Services.DbServiceTypes.Actions[34]['in'];
  'db.account': Services.DbServiceTypes.Actions[35]['in'];
  'db.account.user': Services.DbServiceTypes.Actions[36]['in'];
  'db.migrationGenerated': Services.DbServiceTypes.Actions[37]['in'];
  'db.migrationManual': Services.DbServiceTypes.Actions[38]['in'];
  'db.migrationSeed': Services.DbServiceTypes.Actions[39]['in'];
  'db.testMultiplePrimary': Services.DbServiceTypes.Actions[40]['in'];
  'db.testPrimary': Services.DbServiceTypes.Actions[41]['in'];
  'db.user': Services.DbServiceTypes.Actions[42]['in'];
  'db.user.profile': Services.DbServiceTypes.Actions[43]['in'];
  'db.userByEmail': Services.DbServiceTypes.Actions[44]['in'];
  'db.userByEmail.profile': Services.DbServiceTypes.Actions[45]['in'];
  'db.userByFirstNameAndLastName': Services.DbServiceTypes.Actions[46]['in'];
  'db.userByFirstNameAndLastName.profile': Services.DbServiceTypes.Actions[47]['in'];
  'db.userByUserProfileId': Services.DbServiceTypes.Actions[48]['in'];
  'db.userByUserProfileId.profile': Services.DbServiceTypes.Actions[49]['in'];
  'db.userProfile': Services.DbServiceTypes.Actions[50]['in'];
  'db.userProfile.user': Services.DbServiceTypes.Actions[51]['in'];
  'db.userSearch': Services.DbServiceTypes.Actions[52]['in'];
  'db.countUserSearch': Services.DbServiceTypes.Actions[53]['in'];
  'db.firstUserSearch': Services.DbServiceTypes.Actions[54]['in'];
  'db.firstUserSearch.profile': Services.DbServiceTypes.Actions[55]['in'];
  'db.findUserSearch': Services.DbServiceTypes.Actions[56]['in'];
  'db.accountByNodeId': Services.DbServiceTypes.Actions[57]['in'];
  'db.accountByNodeId.user': Services.DbServiceTypes.Actions[58]['in'];
  'db.migrationGeneratedByNodeId': Services.DbServiceTypes.Actions[59]['in'];
  'db.migrationManualByNodeId': Services.DbServiceTypes.Actions[60]['in'];
  'db.migrationSeedByNodeId': Services.DbServiceTypes.Actions[61]['in'];
  'db.testMultiplePrimaryByNodeId': Services.DbServiceTypes.Actions[62]['in'];
  'db.testPrimaryByNodeId': Services.DbServiceTypes.Actions[63]['in'];
  'db.userByNodeId': Services.DbServiceTypes.Actions[64]['in'];
  'db.userByNodeId.profile': Services.DbServiceTypes.Actions[65]['in'];
  'db.userProfileByNodeId': Services.DbServiceTypes.Actions[66]['in'];
  'db.userProfileByNodeId.user': Services.DbServiceTypes.Actions[67]['in'];
  'db.createAccount': Services.DbServiceTypes.Actions[68]['in'];
  'db.createMigrationGenerated': Services.DbServiceTypes.Actions[69]['in'];
  'db.createMigrationManual': Services.DbServiceTypes.Actions[70]['in'];
  'db.createMigrationSeed': Services.DbServiceTypes.Actions[71]['in'];
  'db.createTestMultiplePrimary': Services.DbServiceTypes.Actions[72]['in'];
  'db.createTestPrimary': Services.DbServiceTypes.Actions[73]['in'];
  'db.createUser': Services.DbServiceTypes.Actions[74]['in'];
  'db.createUserProfile': Services.DbServiceTypes.Actions[75]['in'];
  'db.updateAccountByNodeId': Services.DbServiceTypes.Actions[76]['in'];
  'db.updateAccount': Services.DbServiceTypes.Actions[77]['in'];
  'db.upsertAccount': Services.DbServiceTypes.Actions[78]['in'];
  'db.updateMigrationGeneratedByNodeId': Services.DbServiceTypes.Actions[79]['in'];
  'db.updateMigrationGenerated': Services.DbServiceTypes.Actions[80]['in'];
  'db.upsertMigrationGenerated': Services.DbServiceTypes.Actions[81]['in'];
  'db.updateMigrationManualByNodeId': Services.DbServiceTypes.Actions[82]['in'];
  'db.updateMigrationManual': Services.DbServiceTypes.Actions[83]['in'];
  'db.upsertMigrationManual': Services.DbServiceTypes.Actions[84]['in'];
  'db.updateMigrationSeedByNodeId': Services.DbServiceTypes.Actions[85]['in'];
  'db.updateMigrationSeed': Services.DbServiceTypes.Actions[86]['in'];
  'db.upsertMigrationSeed': Services.DbServiceTypes.Actions[87]['in'];
  'db.updateTestMultiplePrimaryByNodeId': Services.DbServiceTypes.Actions[88]['in'];
  'db.updateTestMultiplePrimary': Services.DbServiceTypes.Actions[89]['in'];
  'db.upsertTestMultiplePrimary': Services.DbServiceTypes.Actions[90]['in'];
  'db.updateTestPrimaryByNodeId': Services.DbServiceTypes.Actions[91]['in'];
  'db.updateTestPrimary': Services.DbServiceTypes.Actions[92]['in'];
  'db.upsertTestPrimary': Services.DbServiceTypes.Actions[93]['in'];
  'db.updateUserByNodeId': Services.DbServiceTypes.Actions[94]['in'];
  'db.updateUser': Services.DbServiceTypes.Actions[95]['in'];
  'db.upsertUser': Services.DbServiceTypes.Actions[96]['in'];
  'db.updateUserByEmail': Services.DbServiceTypes.Actions[97]['in'];
  'db.updateUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[98]['in'];
  'db.updateUserByUserProfileId': Services.DbServiceTypes.Actions[99]['in'];
  'db.updateUserProfileByNodeId': Services.DbServiceTypes.Actions[100]['in'];
  'db.updateUserProfile': Services.DbServiceTypes.Actions[101]['in'];
  'db.upsertUserProfile': Services.DbServiceTypes.Actions[102]['in'];
  'db.deleteAccountByNodeId': Services.DbServiceTypes.Actions[103]['in'];
  'db.deleteAccount': Services.DbServiceTypes.Actions[104]['in'];
  'db.deleteMigrationGeneratedByNodeId': Services.DbServiceTypes.Actions[105]['in'];
  'db.deleteMigrationGenerated': Services.DbServiceTypes.Actions[106]['in'];
  'db.deleteMigrationManualByNodeId': Services.DbServiceTypes.Actions[107]['in'];
  'db.deleteMigrationManual': Services.DbServiceTypes.Actions[108]['in'];
  'db.deleteMigrationSeedByNodeId': Services.DbServiceTypes.Actions[109]['in'];
  'db.deleteMigrationSeed': Services.DbServiceTypes.Actions[110]['in'];
  'db.deleteTestMultiplePrimaryByNodeId': Services.DbServiceTypes.Actions[111]['in'];
  'db.deleteTestMultiplePrimary': Services.DbServiceTypes.Actions[112]['in'];
  'db.deleteTestPrimaryByNodeId': Services.DbServiceTypes.Actions[113]['in'];
  'db.deleteTestPrimary': Services.DbServiceTypes.Actions[114]['in'];
  'db.deleteUserByNodeId': Services.DbServiceTypes.Actions[115]['in'];
  'db.deleteUser': Services.DbServiceTypes.Actions[116]['in'];
  'db.deleteUserByEmail': Services.DbServiceTypes.Actions[117]['in'];
  'db.deleteUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[118]['in'];
  'db.deleteUserByUserProfileId': Services.DbServiceTypes.Actions[119]['in'];
  'db.deleteUserProfileByNodeId': Services.DbServiceTypes.Actions[120]['in'];
  'db.deleteUserProfile': Services.DbServiceTypes.Actions[121]['in'];
  'db.userCustomMutation': Services.DbServiceTypes.Actions[122]['in'];
};

type GetCallReturn = {
  'db.accounts': Services.DbServiceTypes.Actions[0]['out'];
  'db.countAccounts': Services.DbServiceTypes.Actions[1]['out'];
  'db.firstAccounts': Services.DbServiceTypes.Actions[2]['out'];
  'db.firstAccounts.user': Services.DbServiceTypes.Actions[3]['out'];
  'db.findAccounts': Services.DbServiceTypes.Actions[4]['out'];
  'db.migrationGenerateds': Services.DbServiceTypes.Actions[5]['out'];
  'db.countMigrationGenerateds': Services.DbServiceTypes.Actions[6]['out'];
  'db.firstMigrationGenerateds': Services.DbServiceTypes.Actions[7]['out'];
  'db.findMigrationGenerateds': Services.DbServiceTypes.Actions[8]['out'];
  'db.migrationManuals': Services.DbServiceTypes.Actions[9]['out'];
  'db.countMigrationManuals': Services.DbServiceTypes.Actions[10]['out'];
  'db.firstMigrationManuals': Services.DbServiceTypes.Actions[11]['out'];
  'db.findMigrationManuals': Services.DbServiceTypes.Actions[12]['out'];
  'db.migrationSeeds': Services.DbServiceTypes.Actions[13]['out'];
  'db.countMigrationSeeds': Services.DbServiceTypes.Actions[14]['out'];
  'db.firstMigrationSeeds': Services.DbServiceTypes.Actions[15]['out'];
  'db.findMigrationSeeds': Services.DbServiceTypes.Actions[16]['out'];
  'db.testMultiplePrimaries': Services.DbServiceTypes.Actions[17]['out'];
  'db.countTestMultiplePrimaries': Services.DbServiceTypes.Actions[18]['out'];
  'db.firstTestMultiplePrimaries': Services.DbServiceTypes.Actions[19]['out'];
  'db.findTestMultiplePrimaries': Services.DbServiceTypes.Actions[20]['out'];
  'db.testPrimaries': Services.DbServiceTypes.Actions[21]['out'];
  'db.countTestPrimaries': Services.DbServiceTypes.Actions[22]['out'];
  'db.firstTestPrimaries': Services.DbServiceTypes.Actions[23]['out'];
  'db.findTestPrimaries': Services.DbServiceTypes.Actions[24]['out'];
  'db.users': Services.DbServiceTypes.Actions[25]['out'];
  'db.countUsers': Services.DbServiceTypes.Actions[26]['out'];
  'db.firstUsers': Services.DbServiceTypes.Actions[27]['out'];
  'db.firstUsers.profile': Services.DbServiceTypes.Actions[28]['out'];
  'db.findUsers': Services.DbServiceTypes.Actions[29]['out'];
  'db.userProfiles': Services.DbServiceTypes.Actions[30]['out'];
  'db.countUserProfiles': Services.DbServiceTypes.Actions[31]['out'];
  'db.firstUserProfiles': Services.DbServiceTypes.Actions[32]['out'];
  'db.firstUserProfiles.user': Services.DbServiceTypes.Actions[33]['out'];
  'db.findUserProfiles': Services.DbServiceTypes.Actions[34]['out'];
  'db.account': Services.DbServiceTypes.Actions[35]['out'];
  'db.account.user': Services.DbServiceTypes.Actions[36]['out'];
  'db.migrationGenerated': Services.DbServiceTypes.Actions[37]['out'];
  'db.migrationManual': Services.DbServiceTypes.Actions[38]['out'];
  'db.migrationSeed': Services.DbServiceTypes.Actions[39]['out'];
  'db.testMultiplePrimary': Services.DbServiceTypes.Actions[40]['out'];
  'db.testPrimary': Services.DbServiceTypes.Actions[41]['out'];
  'db.user': Services.DbServiceTypes.Actions[42]['out'];
  'db.user.profile': Services.DbServiceTypes.Actions[43]['out'];
  'db.userByEmail': Services.DbServiceTypes.Actions[44]['out'];
  'db.userByEmail.profile': Services.DbServiceTypes.Actions[45]['out'];
  'db.userByFirstNameAndLastName': Services.DbServiceTypes.Actions[46]['out'];
  'db.userByFirstNameAndLastName.profile': Services.DbServiceTypes.Actions[47]['out'];
  'db.userByUserProfileId': Services.DbServiceTypes.Actions[48]['out'];
  'db.userByUserProfileId.profile': Services.DbServiceTypes.Actions[49]['out'];
  'db.userProfile': Services.DbServiceTypes.Actions[50]['out'];
  'db.userProfile.user': Services.DbServiceTypes.Actions[51]['out'];
  'db.userSearch': Services.DbServiceTypes.Actions[52]['out'];
  'db.countUserSearch': Services.DbServiceTypes.Actions[53]['out'];
  'db.firstUserSearch': Services.DbServiceTypes.Actions[54]['out'];
  'db.firstUserSearch.profile': Services.DbServiceTypes.Actions[55]['out'];
  'db.findUserSearch': Services.DbServiceTypes.Actions[56]['out'];
  'db.accountByNodeId': Services.DbServiceTypes.Actions[57]['out'];
  'db.accountByNodeId.user': Services.DbServiceTypes.Actions[58]['out'];
  'db.migrationGeneratedByNodeId': Services.DbServiceTypes.Actions[59]['out'];
  'db.migrationManualByNodeId': Services.DbServiceTypes.Actions[60]['out'];
  'db.migrationSeedByNodeId': Services.DbServiceTypes.Actions[61]['out'];
  'db.testMultiplePrimaryByNodeId': Services.DbServiceTypes.Actions[62]['out'];
  'db.testPrimaryByNodeId': Services.DbServiceTypes.Actions[63]['out'];
  'db.userByNodeId': Services.DbServiceTypes.Actions[64]['out'];
  'db.userByNodeId.profile': Services.DbServiceTypes.Actions[65]['out'];
  'db.userProfileByNodeId': Services.DbServiceTypes.Actions[66]['out'];
  'db.userProfileByNodeId.user': Services.DbServiceTypes.Actions[67]['out'];
  'db.createAccount': Services.DbServiceTypes.Actions[68]['out'];
  'db.createMigrationGenerated': Services.DbServiceTypes.Actions[69]['out'];
  'db.createMigrationManual': Services.DbServiceTypes.Actions[70]['out'];
  'db.createMigrationSeed': Services.DbServiceTypes.Actions[71]['out'];
  'db.createTestMultiplePrimary': Services.DbServiceTypes.Actions[72]['out'];
  'db.createTestPrimary': Services.DbServiceTypes.Actions[73]['out'];
  'db.createUser': Services.DbServiceTypes.Actions[74]['out'];
  'db.createUserProfile': Services.DbServiceTypes.Actions[75]['out'];
  'db.updateAccountByNodeId': Services.DbServiceTypes.Actions[76]['out'];
  'db.updateAccount': Services.DbServiceTypes.Actions[77]['out'];
  'db.upsertAccount': Services.DbServiceTypes.Actions[78]['out'];
  'db.updateMigrationGeneratedByNodeId': Services.DbServiceTypes.Actions[79]['out'];
  'db.updateMigrationGenerated': Services.DbServiceTypes.Actions[80]['out'];
  'db.upsertMigrationGenerated': Services.DbServiceTypes.Actions[81]['out'];
  'db.updateMigrationManualByNodeId': Services.DbServiceTypes.Actions[82]['out'];
  'db.updateMigrationManual': Services.DbServiceTypes.Actions[83]['out'];
  'db.upsertMigrationManual': Services.DbServiceTypes.Actions[84]['out'];
  'db.updateMigrationSeedByNodeId': Services.DbServiceTypes.Actions[85]['out'];
  'db.updateMigrationSeed': Services.DbServiceTypes.Actions[86]['out'];
  'db.upsertMigrationSeed': Services.DbServiceTypes.Actions[87]['out'];
  'db.updateTestMultiplePrimaryByNodeId': Services.DbServiceTypes.Actions[88]['out'];
  'db.updateTestMultiplePrimary': Services.DbServiceTypes.Actions[89]['out'];
  'db.upsertTestMultiplePrimary': Services.DbServiceTypes.Actions[90]['out'];
  'db.updateTestPrimaryByNodeId': Services.DbServiceTypes.Actions[91]['out'];
  'db.updateTestPrimary': Services.DbServiceTypes.Actions[92]['out'];
  'db.upsertTestPrimary': Services.DbServiceTypes.Actions[93]['out'];
  'db.updateUserByNodeId': Services.DbServiceTypes.Actions[94]['out'];
  'db.updateUser': Services.DbServiceTypes.Actions[95]['out'];
  'db.upsertUser': Services.DbServiceTypes.Actions[96]['out'];
  'db.updateUserByEmail': Services.DbServiceTypes.Actions[97]['out'];
  'db.updateUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[98]['out'];
  'db.updateUserByUserProfileId': Services.DbServiceTypes.Actions[99]['out'];
  'db.updateUserProfileByNodeId': Services.DbServiceTypes.Actions[100]['out'];
  'db.updateUserProfile': Services.DbServiceTypes.Actions[101]['out'];
  'db.upsertUserProfile': Services.DbServiceTypes.Actions[102]['out'];
  'db.deleteAccountByNodeId': Services.DbServiceTypes.Actions[103]['out'];
  'db.deleteAccount': Services.DbServiceTypes.Actions[104]['out'];
  'db.deleteMigrationGeneratedByNodeId': Services.DbServiceTypes.Actions[105]['out'];
  'db.deleteMigrationGenerated': Services.DbServiceTypes.Actions[106]['out'];
  'db.deleteMigrationManualByNodeId': Services.DbServiceTypes.Actions[107]['out'];
  'db.deleteMigrationManual': Services.DbServiceTypes.Actions[108]['out'];
  'db.deleteMigrationSeedByNodeId': Services.DbServiceTypes.Actions[109]['out'];
  'db.deleteMigrationSeed': Services.DbServiceTypes.Actions[110]['out'];
  'db.deleteTestMultiplePrimaryByNodeId': Services.DbServiceTypes.Actions[111]['out'];
  'db.deleteTestMultiplePrimary': Services.DbServiceTypes.Actions[112]['out'];
  'db.deleteTestPrimaryByNodeId': Services.DbServiceTypes.Actions[113]['out'];
  'db.deleteTestPrimary': Services.DbServiceTypes.Actions[114]['out'];
  'db.deleteUserByNodeId': Services.DbServiceTypes.Actions[115]['out'];
  'db.deleteUser': Services.DbServiceTypes.Actions[116]['out'];
  'db.deleteUserByEmail': Services.DbServiceTypes.Actions[117]['out'];
  'db.deleteUserByFirstNameAndLastName': Services.DbServiceTypes.Actions[118]['out'];
  'db.deleteUserByUserProfileId': Services.DbServiceTypes.Actions[119]['out'];
  'db.deleteUserProfileByNodeId': Services.DbServiceTypes.Actions[120]['out'];
  'db.deleteUserProfile': Services.DbServiceTypes.Actions[121]['out'];
  'db.userCustomMutation': Services.DbServiceTypes.Actions[122]['out'];
};

type GetEmitParams = {};

export type ServiceNames = Exclude<never | 'db' | 'test', never>;
export type ServiceEventNames = Exclude<never, never>;
export type ServiceActionNames = Exclude<
  | never
  | 'db.accounts'
  | 'db.countAccounts'
  | 'db.firstAccounts'
  | 'db.firstAccounts.user'
  | 'db.findAccounts'
  | 'db.migrationGenerateds'
  | 'db.countMigrationGenerateds'
  | 'db.firstMigrationGenerateds'
  | 'db.findMigrationGenerateds'
  | 'db.migrationManuals'
  | 'db.countMigrationManuals'
  | 'db.firstMigrationManuals'
  | 'db.findMigrationManuals'
  | 'db.migrationSeeds'
  | 'db.countMigrationSeeds'
  | 'db.firstMigrationSeeds'
  | 'db.findMigrationSeeds'
  | 'db.testMultiplePrimaries'
  | 'db.countTestMultiplePrimaries'
  | 'db.firstTestMultiplePrimaries'
  | 'db.findTestMultiplePrimaries'
  | 'db.testPrimaries'
  | 'db.countTestPrimaries'
  | 'db.firstTestPrimaries'
  | 'db.findTestPrimaries'
  | 'db.users'
  | 'db.countUsers'
  | 'db.firstUsers'
  | 'db.firstUsers.profile'
  | 'db.findUsers'
  | 'db.userProfiles'
  | 'db.countUserProfiles'
  | 'db.firstUserProfiles'
  | 'db.firstUserProfiles.user'
  | 'db.findUserProfiles'
  | 'db.account'
  | 'db.account.user'
  | 'db.migrationGenerated'
  | 'db.migrationManual'
  | 'db.migrationSeed'
  | 'db.testMultiplePrimary'
  | 'db.testPrimary'
  | 'db.user'
  | 'db.user.profile'
  | 'db.userByEmail'
  | 'db.userByEmail.profile'
  | 'db.userByFirstNameAndLastName'
  | 'db.userByFirstNameAndLastName.profile'
  | 'db.userByUserProfileId'
  | 'db.userByUserProfileId.profile'
  | 'db.userProfile'
  | 'db.userProfile.user'
  | 'db.userSearch'
  | 'db.countUserSearch'
  | 'db.firstUserSearch'
  | 'db.firstUserSearch.profile'
  | 'db.findUserSearch'
  | 'db.accountByNodeId'
  | 'db.accountByNodeId.user'
  | 'db.migrationGeneratedByNodeId'
  | 'db.migrationManualByNodeId'
  | 'db.migrationSeedByNodeId'
  | 'db.testMultiplePrimaryByNodeId'
  | 'db.testPrimaryByNodeId'
  | 'db.userByNodeId'
  | 'db.userByNodeId.profile'
  | 'db.userProfileByNodeId'
  | 'db.userProfileByNodeId.user'
  | 'db.createAccount'
  | 'db.createMigrationGenerated'
  | 'db.createMigrationManual'
  | 'db.createMigrationSeed'
  | 'db.createTestMultiplePrimary'
  | 'db.createTestPrimary'
  | 'db.createUser'
  | 'db.createUserProfile'
  | 'db.updateAccountByNodeId'
  | 'db.updateAccount'
  | 'db.upsertAccount'
  | 'db.updateMigrationGeneratedByNodeId'
  | 'db.updateMigrationGenerated'
  | 'db.upsertMigrationGenerated'
  | 'db.updateMigrationManualByNodeId'
  | 'db.updateMigrationManual'
  | 'db.upsertMigrationManual'
  | 'db.updateMigrationSeedByNodeId'
  | 'db.updateMigrationSeed'
  | 'db.upsertMigrationSeed'
  | 'db.updateTestMultiplePrimaryByNodeId'
  | 'db.updateTestMultiplePrimary'
  | 'db.upsertTestMultiplePrimary'
  | 'db.updateTestPrimaryByNodeId'
  | 'db.updateTestPrimary'
  | 'db.upsertTestPrimary'
  | 'db.updateUserByNodeId'
  | 'db.updateUser'
  | 'db.upsertUser'
  | 'db.updateUserByEmail'
  | 'db.updateUserByFirstNameAndLastName'
  | 'db.updateUserByUserProfileId'
  | 'db.updateUserProfileByNodeId'
  | 'db.updateUserProfile'
  | 'db.upsertUserProfile'
  | 'db.deleteAccountByNodeId'
  | 'db.deleteAccount'
  | 'db.deleteMigrationGeneratedByNodeId'
  | 'db.deleteMigrationGenerated'
  | 'db.deleteMigrationManualByNodeId'
  | 'db.deleteMigrationManual'
  | 'db.deleteMigrationSeedByNodeId'
  | 'db.deleteMigrationSeed'
  | 'db.deleteTestMultiplePrimaryByNodeId'
  | 'db.deleteTestMultiplePrimary'
  | 'db.deleteTestPrimaryByNodeId'
  | 'db.deleteTestPrimary'
  | 'db.deleteUserByNodeId'
  | 'db.deleteUser'
  | 'db.deleteUserByEmail'
  | 'db.deleteUserByFirstNameAndLastName'
  | 'db.deleteUserByUserProfileId'
  | 'db.deleteUserProfileByNodeId'
  | 'db.deleteUserProfile'
  | 'db.userCustomMutation',
  never
>;
export type ServiceNamesEmitGroup = ServiceNames | ServiceNames[];
